### ISSUE TITLE
Logo needs new color

### ISSUE THREAD

**Issue by jchoi25** [aayu3/UIUCCrimeMap#28]
I changed the header color to orange so that it matches the orange-white themed police department website and now the logo is barely visible. I think changing the font color to white could be better.

**Comment by aayu3** [comment]
Yeah sure, that makes sense.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

From: Juyoung ***@***.***>
Sent: Sunday, May 30, 2021 9:16 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [aayu3/UIUCCrimeMap] Logo needs new color (#28)


I changed the header color to orange so that it matches the orange-white themed police department website and now the logo is barely visible. I think changing the font color to white could be better.

**Comment by jchoi25** [comment]
solved
